name: CS224W
channels:
  - conda-forge
  - defaults
dependencies:
  - aom=3.6.0=hcec6c5f_0
  - appnope=0.1.4=pyhd8ed1ab_1
  - asttokens=3.0.0=pyhd8ed1ab_1
  - biopython=1.78=py312h6c40b1e_0
  - blas=1.0=openblas
  - bottleneck=1.4.2=py312ha2b695f_0
  - brotli-python=1.0.9=py312h6d0c2b6_9
  - bzip2=1.0.8=h6c40b1e_6
  - ca-certificates=2025.7.15=hecd8cb5_0
  - cairo=1.16.0=h08824b9_6
  - comm=0.2.3=pyhe01879c_0
  - contourpy=1.3.1=py312h1962661_0
  - cycler=0.11.0=pyhd3eb1b0_0
  - dav1d=1.2.1=h6c40b1e_0
  - debugpy=1.8.11=py312h6d0c2b6_0
  - decorator=5.2.1=pyhd8ed1ab_0
  - exceptiongroup=1.3.0=pyhd8ed1ab_0
  - executing=2.2.1=pyhd8ed1ab_0
  - expat=2.7.1=h6d0c2b6_0
  - fontconfig=2.14.1=h269ac6a_3
  - fonttools=4.55.3=py312h46256e1_0
  - freetype=2.13.3=h02243ff_0
  - fribidi=1.0.10=haf1e3a3_0
  - gensim=4.3.3=py312h77d3abe_0
  - gettext=0.21.0=h4e8c18a_2
  - graphite2=1.3.14=he9d5cce_1
  - harfbuzz=10.2.0=h060d35a_1
  - icu=73.1=hcec6c5f_0
  - importlib-metadata=8.7.0=pyhe01879c_1
  - intel-openmp=2023.1.0=ha357a0b_43548
  - ipykernel=6.30.1=pyh92f572d_0
  - ipython=9.6.0=pyhfa0c392_0
  - ipython_pygments_lexers=1.1.1=pyhd8ed1ab_0
  - jedi=0.19.2=pyhd8ed1ab_1
  - jpeg=9e=h46256e1_3
  - jupyter_client=8.6.3=pyhd8ed1ab_1
  - jupyter_core=5.8.1=pyh31011fe_0
  - kiwisolver=1.4.8=py312h6d0c2b6_0
  - krb5=1.21.3=h37d8d59_0
  - lcms2=2.16=h31d93a5_1
  - lerc=4.0.0=h6d0c2b6_0
  - libavif=1.1.1=h46256e1_0
  - libcxx=19.1.7=haebbb44_3
  - libdeflate=1.22=h46256e1_0
  - libedit=3.1.20250104=pl5321ha958ccf_0
  - libffi=3.4.4=hecd8cb5_1
  - libgfortran=5.0.0=11_3_0_hecd8cb5_28
  - libgfortran5=11.3.0=h9dfd629_28
  - libglib=2.84.2=heb90364_0
  - libiconv=1.16=h6c40b1e_3
  - libopenblas=0.3.29=h3f8574a_0
  - libpng=1.6.39=h6c40b1e_0
  - libsodium=1.0.20=hfdf4475_0
  - libtiff=4.7.0=h2dfa3ea_0
  - libwebp-base=1.3.2=h46256e1_1
  - libxml2=2.13.8=h6070cd6_0
  - llvm-openmp=19.1.7=h5048363_2
  - lz4-c=1.9.4=hcec6c5f_1
  - matplotlib=3.10.0=py312hecd8cb5_0
  - matplotlib-base=3.10.0=py312h919b35b_0
  - matplotlib-inline=0.1.7=pyhd8ed1ab_1
  - mkl=2023.1.0=h8e150cf_43560
  - mkl-service=2.4.0=py312h46256e1_2
  - ncurses=6.5=h923df54_0
  - nest-asyncio=1.6.0=pyhd8ed1ab_1
  - numexpr=2.11.0=py312h20bc273_0
  - numpy=1.26.4=py312h7d6adbd_0
  - numpy-base=1.26.4=py312hbb3573c_0
  - openjpeg=2.5.2=h2d09ccc_1
  - openssl=3.5.4=h230baf5_0
  - packaging=25.0=pyh29332c3_1
  - pandas=2.3.1=py312hebe84f7_0
  - parso=0.8.5=pyhcf101f3_0
  - pcre2=10.42=h9b97e30_1
  - pexpect=4.9.0=pyhd8ed1ab_1
  - pickleshare=0.7.5=pyhd8ed1ab_1004
  - pillow=11.3.0=py312h25d8182_0
  - pip=25.2=pyhc872135_0
  - pixman=0.46.4=hb254d66_0
  - platformdirs=4.4.0=pyhcf101f3_0
  - prompt-toolkit=3.0.52=pyha770c72_0
  - psutil=5.9.0=py312h46256e1_1
  - ptyprocess=0.7.0=pyhd8ed1ab_1
  - pure_eval=0.2.3=pyhd8ed1ab_1
  - pybind11-abi=5=hd3eb1b0_0
  - pygments=2.19.2=pyhd8ed1ab_0
  - pyparsing=3.2.0=py312hecd8cb5_0
  - python=3.12.11=he8d2d4c_0
  - python-dateutil=2.9.0.post0=pyhe01879c_2
  - python-tzdata=2025.2=pyhd3eb1b0_0
  - pytz=2025.2=py312hecd8cb5_0
  - pyzmq=26.2.0=py312h6d0c2b6_0
  - readline=8.3=h49f2429_0
  - seaborn=0.13.2=py312hecd8cb5_3
  - setuptools=78.1.1=py312hecd8cb5_0
  - six=1.17.0=pyhe01879c_1
  - smart_open=5.2.1=py312hecd8cb5_0
  - sqlite=3.50.2=hc8b0dd6_1
  - stack_data=0.6.3=pyhd8ed1ab_1
  - tbb=2021.8.0=ha357a0b_0
  - tk=8.6.15=h3a5a201_0
  - tornado=6.5.1=py312h46256e1_0
  - traitlets=5.14.3=pyhd8ed1ab_1
  - typing_extensions=4.15.0=pyhcf101f3_0
  - tzdata=2025b=h04d1e81_0
  - unicodedata2=15.1.0=py312h46256e1_1
  - wcwidth=0.2.14=pyhd8ed1ab_0
  - wheel=0.45.1=py312hecd8cb5_0
  - xz=5.6.4=h46256e1_1
  - zeromq=4.3.5=h6c33b1e_9
  - zipp=3.23.0=pyhd8ed1ab_0
  - zlib=1.2.13=h4b97444_1
  - zstd=1.5.6=h138b38a_0
  - pip:
      - absl-py==2.3.1
      - aiohappyeyeballs==2.6.1
      - aiohttp==3.13.0
      - aiosignal==1.4.0
      - antlr4-python3-runtime==4.9.3
      - attrs==25.4.0
      - biotite==1.4.0
      - biotraj==1.2.2
      - certifi==2025.10.5
      - charset-normalizer==3.4.3
      - deepspeed==0.5.9
      - dllogger==1.1.0
      - dm-tree==0.1.9
      - einops==0.8.1
      - fair-esm==2.0.0
      - filelock==3.20.0
      - frozenlist==1.8.0
      - fsspec==2025.9.0
      - hjson==3.1.0
      - idna==3.10
      - jinja2==3.1.6
      - joblib==1.5.2
      - lightning-utilities==0.15.2
      - littleutils==0.2.4
      - markupsafe==3.0.3
      - ml-collections==1.1.0
      - mpmath==1.3.0
      - msgpack==1.1.2
      - multidict==6.7.0
      - networkx==3.5
      - ninja==1.13.0
      - ogb==1.3.6
      - omegaconf==2.3.0
      - outdated==0.2.2
      - propcache==0.4.1
      - py-cpuinfo==9.0.0
      - pytorch-lightning==2.5.5
      - pyyaml==6.0.3
      - requests==2.32.5
      - scikit-learn==1.7.2
      - scipy==1.16.2
      - sympy==1.14.0
      - threadpoolctl==3.6.0
      - torch==2.2.2
      - torch-geometric==2.7.0
      - torch-scatter==2.1.2
      - torch-sparse==0.6.18
      - torchmetrics==1.8.2
      - torchvision==0.17.2
      - tqdm==4.67.1
      - urllib3==2.5.0
      - wrapt==1.17.3
      - xxhash==3.6.0
      - yarl==1.22.0
prefix: /Users/alexandrakim/opt/anaconda3/envs/CS224W
