name: cs224w
channels:
  - defaults
dependencies:
  - ca-certificates=2025.11.4=hca03da5_0
  - libcxx=20.1.8=hd7fd590_1
  - libffi=3.4.4=hca03da5_1
  - libzlib=1.3.1=h5f15de7_0
  - ncurses=6.5=hee39554_0
  - openssl=3.0.18=h9b4081a_0
  - pip=24.2=py38hca03da5_0
  - python=3.8.20=hb885b13_0
  - readline=8.3=h0b18652_0
  - setuptools=75.1.0=py38hca03da5_0
  - sqlite=3.51.0=hab6afd1_0
  - tk=8.6.15=hcd8a7d5_0
  - wheel=0.44.0=py38hca03da5_0
  - xz=5.6.4=h80987f9_1
  - zlib=1.3.1=h5f15de7_0
  - pip:
      - 2to3==1.0
      - fsspec==2025.3.0
      - gensim==4.3.3
      - jinja2==3.1.6
      - markupsafe==2.1.5
      - mpmath==1.3.0
      - networkx==3.1
      - numpy==1.24.4
      - scipy==1.10.1
      - smart-open==7.3.1
      - sympy==1.13.3
      - torch==2.4.1
      - tqdm==4.67.1
      - typing-extensions==4.13.2
      - wrapt==2.0.1

